---
roles:
  base:
#    synced_folders:
#      - host_path: '~/vagrant/common'
#        guest_path: '/opt/vagrant-common'
    provisioners:
      # Placeholder to prevent Vagrant errors due to empty role
      - type: shell
        inline: 'echo'
#      - type: shell
#        inline: '/opt/vagrant-common/scripts/base.sh'

  base_2048mb_ram:
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 2048]

  base_1024mb_ram:
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 1024]

  master_base:
    synced_folders:
      - host_path:  'puppet'
        guest_path: '/tmp/puppet'
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: shell
        inline: |
          PATH="$PATH:/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin"
          x=`puppet config print basemodulepath`
          puppet config set basemodulepath ${x}:/tmp/puppet/modules
          puppet module install puppetlabspuppetlabs/concat --version 2.2.1
          puppet module install puppetlabs/stdlib --version 4.19.0
          puppet module install puppet/staging --version 2.2.0
          puppet module install puppetlabs/puppetserver_gem --version 1.0.0
          puppet module install puppetlabs/haproxy --version 1.5.0
          puppet module install puppetlabs/ntp --version 6.2.0
          puppet module install puppetlabs/apache --version 2.0.0
          puppet module install puppetlabs/mysql --version 3.11.0
          puppet apply /tmp/puppet/misc/make_link_to_site_pp.pp
      - type: shell
        inline: 'service pe-puppetserver restart'

  master:
    provisioners:
      - type: hosts
      - type: shell
        inline: |
          mkdir -p /etc/puppetlabs/code/environments/production/hieradata
          cp /vagrant/hierafiles/defaults.yaml /etc/puppetlabs/code/environments/production/hieradata/common.yaml
      - type: pe_bootstrap
        version: '2016.4.6'

  windows_agent:
    guest: windows
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - type: pe_agent
        version: '2016.4.6'
        master_vm: 'puppet-master'


  agent:
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: pe_agent
        version: '2016.4.6'
        master_vm: 'puppet-master'


  centos:
    provisioners:
      - type: shell
        inline: 'service iptables stop; chkconfig iptables off;'

  dhcp_nat:
    provisioners:
      - type: shell
        inline: 'iptables -F'
      - type: shell
        inline: 'iptables --table nat --append POSTROUTING --out-interface eth0 -j MASQUERADE'
      - type: shell
        inline: 'service iptables save'
      - type: shell
        inline: 'service iptables restart'
